/**
 * ============================================================
 *  COMSOL Multiphysics Integration Module
 *  ─────────────────────────────────────────
 *  - Export atmosphere grid as COMSOL-compatible CSV
 *  - Generate COMSOL Java API model script
 *  - Export ray path for COMSOL comparison
 *  - COMSOL LiveLink parameter bridge
 * ============================================================
 */

class COMSOLBridge {
    constructor() {
        this.modelName = 'FSO_AtmosphericChannel';
        this.version = '6.2'; // COMSOL version target
    }

    /**
     * Export atmosphere grid as CSV for COMSOL interpolation function import
     * Format: x, y, z, n, temperature, pressure
     */
    exportGridCSV(atmosphere) {
        const atm = atmosphere;
        const cs = atm.cellSize;
        let csv = '% COMSOL Multiphysics - Atmosphere Grid Data\n';
        csv += '% Generated by FSO Physics Engine\n';
        csv += `% Grid: ${atm.gridX}x${atm.gridY}x${atm.gridZ}, Cell Size: ${cs}m\n`;
        csv += `% Total Range: ${atm.gridX * cs}m x ${atm.gridY * cs}m x ${atm.gridZ * cs}m\n`;
        csv += `% Date: ${new Date().toISOString()}\n`;
        csv += '% x[m], y[m], z[m], n[-], T[C], P[Pa]\n';

        for (let iz = 0; iz < atm.gridZ; iz++) {
            for (let iy = 0; iy < atm.gridY; iy++) {
                for (let ix = 0; ix < atm.gridX; ix++) {
                    const x = (ix + 0.5) * cs;
                    const y = (iy + 0.5) * cs;
                    const z = (iz + 0.5) * cs;
                    const idx = atm.index(ix, iy, iz);
                    const n = atm.grid[idx];
                    const T = atm.temperature[idx];
                    // Approximate pressure from altitude (barometric formula)
                    const P = 101325 * Math.exp(-0.0001184 * z);
                    csv += `${x.toFixed(2)}, ${y.toFixed(2)}, ${z.toFixed(2)}, ${n.toFixed(10)}, ${T.toFixed(2)}, ${P.toFixed(1)}\n`;
                }
            }
        }
        return csv;
    }

    /**
     * Export ray trace path as CSV for COMSOL overlay / comparison
     */
    exportRayPathCSV(traceResult) {
        let csv = '% COMSOL Multiphysics - Ray Path Data\n';
        csv += '% Generated by FSO Physics Engine\n';
        csv += `% Date: ${new Date().toISOString()}\n`;
        csv += '% step, x[m], y[m], z[m], dir_x, dir_y, dir_z, n, distance[m]\n';

        for (let i = 0; i < traceResult.path.length; i++) {
            const p = traceResult.path[i];
            csv += `${i}, ${p.position.x.toFixed(6)}, ${p.position.y.toFixed(6)}, ${p.position.z.toFixed(6)}, `;
            csv += `${p.direction.x.toFixed(8)}, ${p.direction.y.toFixed(8)}, ${p.direction.z.toFixed(8)}, `;
            csv += `${p.n.toFixed(10)}, ${p.distance.toFixed(6)}\n`;
        }
        return csv;
    }

    /**
     * Generate COMSOL Java API Model Script (.java)
     * This creates a complete COMSOL model with:
     * - 3D geometry matching the atmosphere grid
     * - Geometric Optics (ray) physics
     * - Temperature-dependent refractive index
     * - Mesh configuration
     */
    generateModelScript(atmosphere, sourcePos, targetPos, params = {}) {
        const atm = atmosphere;
        const cs = atm.cellSize;
        const totalX = atm.gridX * cs;
        const totalY = atm.gridY * cs;
        const totalZ = atm.gridZ * cs;

        const {
            wavelength = 1550e-9,  // 1550nm (telecom)
            laserPower = 0.01,     // 10 mW
            beamWaist = 0.002,     // 2mm beam waist
            numRays = 100
        } = params;

        return `/*
 * ============================================================
 *  COMSOL Multiphysics Model Script
 *  FSO Atmospheric Channel - Ray Optics Simulation
 *  ─────────────────────────────────────────────────
 *  Auto-generated by FSO Physics Engine
 *  Date: ${new Date().toISOString()}
 * ============================================================
 *
 *  Bu script'i COMSOL'da çalıştırmak için:
 *  1. COMSOL Multiphysics'i açın
 *  2. File → Application Builder veya Developer Tab
 *  3. Bu .java dosyasını import edin
 *  4. Ya da COMSOL with MATLAB: mphload ile yükleyin
 *
 *  Gerekli COMSOL modülleri:
 *  - Ray Optics Module
 *  - Heat Transfer Module (opsiyonel)
 * ============================================================
 */

import com.comsol.model.*;
import com.comsol.model.util.*;

public class ${this.modelName} {

    public static Model run() {
        
        Model model = ModelUtil.create("Model");
        model.modelPath("");
        model.label("FSO_Atmospheric_Channel_6km.mph");

        // ── Parameters ─────────────────────────────────────
        model.param().set("L_total", "${totalX} [m]", "Total propagation distance");
        model.param().set("W_domain", "${totalY} [m]", "Domain width");
        model.param().set("H_domain", "${totalZ} [m]", "Domain height");
        model.param().set("lambda0", "${wavelength} [m]", "Wavelength");
        model.param().set("P_laser", "${laserPower} [W]", "Laser power");
        model.param().set("w0", "${beamWaist} [m]", "Beam waist radius");
        model.param().set("n_base", "${atm.n_base}", "Base refractive index of air");
        model.param().set("T_base", "${params.baseTemp || 20} [degC]", "Base temperature");
        model.param().set("cell_size", "${cs} [m]", "Grid cell size");
        model.param().set("n_rays", "${numRays}", "Number of rays");

        // Edlén equation parameters
        model.param().set("A_edlen", "0.000293", "Edlén coefficient A");
        model.param().set("T_ref", "288.15 [K]", "Reference temperature");

        // Source & receiver positions
        model.param().set("src_x", "${sourcePos.x} [m]", "Source X");
        model.param().set("src_y", "${sourcePos.y} [m]", "Source Y");
        model.param().set("src_z", "${sourcePos.z} [m]", "Source Z");
        model.param().set("rcv_x", "${targetPos.x} [m]", "Receiver X");
        model.param().set("rcv_y", "${targetPos.y} [m]", "Receiver Y");
        model.param().set("rcv_z", "${targetPos.z} [m]", "Receiver Z");

        // ── Component ──────────────────────────────────────
        model.component().create("comp1", true);

        // ── Geometry ───────────────────────────────────────
        model.component("comp1").geom().create("geom1", 3);
        model.component("comp1").geom("geom1").lengthUnit("m");

        // Main atmospheric domain
        model.component("comp1").geom("geom1").create("blk1", "Block");
        model.component("comp1").geom("geom1").feature("blk1")
            .set("size", new String[]{"L_total", "W_domain", "H_domain"});
        model.component("comp1").geom("geom1").feature("blk1")
            .set("pos", new String[]{"0", "0", "0"});
        model.component("comp1").geom("geom1").feature("blk1")
            .label("Atmospheric_Channel");

        model.component("comp1").geom("geom1").run();

        // ── Interpolation Function (n from CSV) ───────────
        // Import the atmosphere grid CSV as interpolation function
        model.func().create("int1", "Interpolation");
        model.func("int1").label("Refractive_Index_Field");
        model.func("int1").set("source", "file");
        model.func("int1").set("filename", "atmosphere_grid.csv");
        model.func("int1").set("nargs", "3");
        model.func("int1").set("argunit", "m, m, m");
        model.func("int1").set("fununit", "1");
        model.func("int1").set("interp", "linear");

        // Analytic fallback: Edlén equation
        model.func().create("an1", "Analytic");
        model.func("an1").label("Edlen_Equation");
        model.func("an1").set("expr", "1 + A_edlen * T_ref / (T + 273.15)");
        model.func("an1").set("args", new String[]{"T"});
        model.func("an1").set("argunit", "degC");
        model.func("an1").set("fununit", "1");

        // ── Materials ──────────────────────────────────────
        model.component("comp1").material().create("mat1", "Common");
        model.component("comp1").material("mat1").label("Atmospheric_Air");
        model.component("comp1").material("mat1").propertyGroup("def")
            .set("refractiveindex", "int1(x, y, z)");
        // Alternative: use Edlén if no CSV
        // .set("refractiveindex", "an1(T)");

        model.component("comp1").material("mat1").propertyGroup("def")
            .set("density", "1.225[kg/m^3]");

        // ── Physics: Ray Optics ────────────────────────────
        model.component("comp1").physics().create("gop", "GeometricalOptics", "geom1");
        model.component("comp1").physics("gop").label("Ray_Optics");

        // Graded-index medium (continuous n variation)
        // This is KEY: tells COMSOL to use Snell's law through graded medium
        model.component("comp1").physics("gop")
            .prop("RayPropertySelection").set("RayPropertySelection", "GradedIndex");

        // Set wavelength
        model.component("comp1").physics("gop")
            .prop("WavelengthSpecification").set("lambda0", "lambda0");

        // Release: Point source (laser)
        model.component("comp1").physics("gop").create("relp1", "ReleaseFromPoint", -1);
        model.component("comp1").physics("gop").feature("relp1")
            .set("x0", new String[]{"src_x", "src_y", "src_z"});
        model.component("comp1").physics("gop").feature("relp1")
            .set("N", "n_rays");
        // Conical release toward receiver
        model.component("comp1").physics("gop").feature("relp1")
            .set("ReleaseType", "Conical");
        model.component("comp1").physics("gop").feature("relp1")
            .set("coneAxis", new String[]{
                "rcv_x - src_x", "rcv_y - src_y", "rcv_z - src_z"
            });
        model.component("comp1").physics("gop").feature("relp1")
            .set("alphaCone", "0.001 [rad]"); // 1 mrad divergence

        // Wall: Absorbing at receiver end
        // (Boundary at x = L_total)
        model.component("comp1").physics("gop").create("wall1", "Wall", 2);
        model.component("comp1").physics("gop").feature("wall1")
            .set("WallCondition", "Disappear");
        model.component("comp1").physics("gop").feature("wall1")
            .label("Receiver_Plane");

        // ── Mesh ───────────────────────────────────────────
        model.component("comp1").mesh().create("mesh1");

        // For ray optics, mesh is for medium property interpolation
        model.component("comp1").mesh("mesh1").create("map1", "Mapped");
        model.component("comp1").mesh("mesh1").feature("map1")
            .create("dis1", "Distribution");
        model.component("comp1").mesh("mesh1").feature("map1").feature("dis1")
            .set("numelem", "${atm.gridX}");

        model.component("comp1").mesh("mesh1").create("swe1", "Sweep");
        model.component("comp1").mesh("mesh1").feature("swe1")
            .create("dis1", "Distribution");
        model.component("comp1").mesh("mesh1").feature("swe1").feature("dis1")
            .set("numelem", "${atm.gridZ}");

        model.component("comp1").mesh("mesh1").run();

        // ── Study ──────────────────────────────────────────
        model.study().create("std1");
        model.study("std1").create("rtrac", "RayTracing");
        model.study("std1").feature("rtrac")
            .set("tlist", "range(0, L_total/299792458/100, L_total/299792458)");
        // Time range: 0 to propagation time in ~100 steps

        // ── Solution ───────────────────────────────────────
        model.sol().create("sol1");
        model.sol("sol1").study("std1");
        model.sol("sol1").create("st1", "StudyStep");
        model.sol("sol1").create("v1", "Variables");
        model.sol("sol1").create("t1", "Time");

        model.sol("sol1").feature("t1").set("tlist", 
            "range(0, L_total/299792458/100, L_total/299792458)");

        // ── Results ────────────────────────────────────────
        // Ray trajectory plot
        model.result().create("pg1", "PlotGroup3D");
        model.result("pg1").label("Ray_Trajectories");
        model.result("pg1").create("rtp1", "RayTrajectories");
        model.result("pg1").feature("rtp1").set("linetype", "tube");
        model.result("pg1").feature("rtp1").set("tuberadiusexpr", "0.5");
        model.result("pg1").feature("rtp1").set("coloring", "uniform");
        model.result("pg1").feature("rtp1").set("color", "blue");

        // Refractive index slice
        model.result().create("pg2", "PlotGroup3D");
        model.result("pg2").label("Refractive_Index_Field");
        model.result("pg2").create("slc1", "Slice");
        model.result("pg2").feature("slc1").set("expr", "gop.nmed");
        model.result("pg2").feature("slc1").set("descr", "Refractive Index");

        // Ray intensity at receiver
        model.result().create("pg3", "PlotGroup2D");
        model.result("pg3").label("Receiver_Intensity");
        model.result("pg3").set("titletype", "manual");
        model.result("pg3").set("title", "Intensity at Receiver Plane");

        return model;
    }

    public static void main(String[] args) {
        Model model = run();
        model.save("FSO_Atmospheric_Channel_6km");
    }
}
`;
    }

    /**
     * Generate COMSOL MATLAB LiveLink script
     */
    generateMatlabScript(atmosphere, sourcePos, targetPos, params = {}) {
        const atm = atmosphere;
        const cs = atm.cellSize;
        const totalX = atm.gridX * cs;
        const totalY = atm.gridY * cs;
        const totalZ = atm.gridZ * cs;

        return `%% ============================================================
%%  COMSOL LiveLink for MATLAB – FSO Atmospheric Channel
%%  ─────────────────────────────────────────────────────────
%%  Auto-generated by FSO Physics Engine
%%  Date: ${new Date().toISOString()}
%%
%%  Kullanım:
%%    1. MATLAB'da COMSOL LiveLink'i başlatın:
%%       >> mphstart
%%    2. Bu script'i çalıştırın
%%    3. Sonuçları karşılaştırma için export edin
%% ============================================================

clear; clc;

%% ── Model Oluşturma ─────────────────────────────────
import com.comsol.model.*
import com.comsol.model.util.*

model = ModelUtil.create('FSO_6km');
model.label('FSO_Atmospheric_Channel_6km.mph');

%% ── Parametreler ─────────────────────────────────────
model.param.set('L_total', '${totalX} [m]', 'Toplam mesafe');
model.param.set('W_domain', '${totalY} [m]', 'Domain genişliği');
model.param.set('H_domain', '${totalZ} [m]', 'Domain yüksekliği');
model.param.set('lambda0', '${params.wavelength || 1550e-9} [m]', 'Dalga boyu');
model.param.set('n_base', '${atm.n_base}', 'Baz kırılma indisi');
model.param.set('T_base', '${params.baseTemp || 20} [degC]', 'Baz sıcaklık');
model.param.set('cell_size', '${cs} [m]', 'Hücre boyutu');

%% ── CSV Veri Yükleme ─────────────────────────────────
% atmosphere_grid.csv dosyasını yükle
data = readmatrix('atmosphere_grid.csv');
x_data = data(:,1);
y_data = data(:,2);
z_data = data(:,3);
n_data = data(:,4);
T_data = data(:,5);

%% ── Geometri ─────────────────────────────────────────
comp1 = model.component.create('comp1', true);
geom1 = comp1.geom.create('geom1', 3);
geom1.lengthUnit('m');

% Atmosferik kanal bloğu
blk1 = geom1.create('blk1', 'Block');
blk1.set('size', {'L_total', 'W_domain', 'H_domain'});
blk1.set('pos', {'0', '0', '0'});
blk1.label('Atmosferik_Kanal');

geom1.run;

%% ── İnterpolasyon Fonksiyonu ─────────────────────────
% Kırılma indisi alanını dosyadan yükle
int1 = model.func.create('int1', 'Interpolation');
int1.label('Kirilma_Indisi_Alani');
int1.set('source', 'file');
int1.set('filename', 'atmosphere_grid.csv');
int1.set('nargs', '3');
int1.set('interp', 'linear');

%% ── Malzeme ──────────────────────────────────────────
mat1 = comp1.material.create('mat1', 'Common');
mat1.label('Atmosferik_Hava');
mat1.propertyGroup('def').set('refractiveindex', 'int1(x, y, z)');

%% ── Fizik: Işın Optiği ──────────────────────────────
gop = comp1.physics.create('gop', 'GeometricalOptics', 'geom1');
gop.label('Isin_Optigi');

% Graded-index ortam (sürekli n değişimi)
gop.prop('RayPropertySelection').set('RayPropertySelection', 'GradedIndex');
gop.prop('WavelengthSpecification').set('lambda0', 'lambda0');

% Kaynak noktası (lazer)
relp1 = gop.create('relp1', 'ReleaseFromPoint', -1);
relp1.set('x0', {'${sourcePos.x}', '${sourcePos.y}', '${sourcePos.z}'});
relp1.set('N', '100');
relp1.set('ReleaseType', 'Conical');
relp1.set('coneAxis', {'${targetPos.x - sourcePos.x}', '${targetPos.y - sourcePos.y}', '${targetPos.z - sourcePos.z}'});
relp1.set('alphaCone', '0.001 [rad]');

%% ── Mesh ─────────────────────────────────────────────
mesh1 = comp1.mesh.create('mesh1');
mesh1.autoMeshSize(4); % Fine mesh

%% ── Study ────────────────────────────────────────────
std1 = model.study.create('std1');
rtrac = std1.create('rtrac', 'RayTracing');
t_prop = ${totalX} / 299792458; % Propagation time
rtrac.set('tlist', ['range(0, ' num2str(t_prop/100) ', ' num2str(t_prop) ')']);

%% ── Çözüm ────────────────────────────────────────────
fprintf('Çözüm başlatılıyor...\\n');
model.study('std1').run;
fprintf('Çözüm tamamlandı!\\n');

%% ── Sonuçlar ─────────────────────────────────────────
% Ray trajectory verisini çıkar
pg1 = model.result.create('pg1', 'PlotGroup3D');
pg1.label('Isin_Yollari');
rtp1 = pg1.create('rtp1', 'RayTrajectories');
rtp1.set('linetype', 'tube');

% Alıcı düzleminde yoğunluk
pg2 = model.result.create('pg2', 'PlotGroup2D');
pg2.label('Alici_Yogunluk');

%% ── Model Kaydetme ──────────────────────────────────
mphsave(model, 'FSO_Atmospheric_Channel_6km.mph');
fprintf('Model kaydedildi: FSO_Atmospheric_Channel_6km.mph\\n');

%% ── Karşılaştırma İçin Veri Export ──────────────────
% COMSOL ray path verilerini export et
fprintf('\\n=== FSO Motor Karşılaştırma Verileri ===\\n');
fprintf('FSO Motor ray path: ray_path.csv\\n');
fprintf('COMSOL model: FSO_Atmospheric_Channel_6km.mph\\n');
fprintf('Her iki sonucu karşılaştırarak doğrulama yapabilirsiniz.\\n');
`;
    }

    /**
     * Generate COMSOL Parameters file (.txt)
     * Can be directly imported into COMSOL via Parameters → Load from File
     */
    generateParametersFile(atmosphere, sourcePos, targetPos, params = {}) {
        const atm = atmosphere;
        const cs = atm.cellSize;
        const totalX = atm.gridX * cs;
        const totalY = atm.gridY * cs;
        const totalZ = atm.gridZ * cs;

        return `% COMSOL Parameters File
% Import via: Parameters → Load from File
% Generated: ${new Date().toISOString()}
L_total ${totalX}[m] Total propagation distance (${(totalX/1000).toFixed(1)} km)
W_domain ${totalY}[m] Domain width
H_domain ${totalZ}[m] Domain height
cell_size ${cs}[m] Grid cell size
lambda0 ${params.wavelength || 1550e-9}[m] Laser wavelength
P_laser ${params.laserPower || 0.01}[W] Laser power
w0 ${params.beamWaist || 0.002}[m] Beam waist radius
n_base ${atm.n_base} Base refractive index
T_base ${params.baseTemp || 20}[degC] Base temperature
delta_T ${params.deltaT || 15}[K] Temperature variation
src_x ${sourcePos.x}[m] Source X position
src_y ${sourcePos.y}[m] Source Y position
src_z ${sourcePos.z}[m] Source Z position
rcv_x ${targetPos.x}[m] Receiver X position
rcv_y ${targetPos.y}[m] Receiver Y position
rcv_z ${targetPos.z}[m] Receiver Z position
alpha_div 0.001[rad] Beam divergence angle
Cn2 1e-14[m^(-2/3)] Refractive index structure parameter
`;
    }

    /**
     * Download helper – triggers browser download
     */
    static download(content, filename, mimeType = 'text/plain') {
        const blob = new Blob([content], { type: mimeType });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }
}

window.COMSOLBridge = COMSOLBridge;
